#include <dpn/protocol/get_config.hpp>
#include <dpn/protocol/config.hpp>
#include <dpn/protocol/asset.hpp>
#include <dpn/protocol/types.hpp>
#include <dpn/protocol/version.hpp>

namespace dpn { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
#ifdef DPN_ENABLE_SMT
   result[ "DPN_ENABLE_SMT" ] = true;
   result["SMT_MAX_VOTABLE_ASSETS"] = SMT_MAX_VOTABLE_ASSETS;
   result["SMT_VESTING_WITHDRAW_INTERVAL_SECONDS"] = SMT_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["SMT_UPVOTE_LOCKOUT"] = SMT_UPVOTE_LOCKOUT;
   result["SMT_EMISSION_MIN_INTERVAL_SECONDS"] = SMT_EMISSION_MIN_INTERVAL_SECONDS;
   result["SMT_EMIT_INDEFINITELY"] = SMT_EMIT_INDEFINITELY;
   result["SMT_MAX_NOMINAL_VOTES_PER_DAY"] = SMT_MAX_NOMINAL_VOTES_PER_DAY;
   result["SMT_MAX_VOTES_PER_REGENERATION"] = SMT_MAX_VOTES_PER_REGENERATION;
   result["SMT_DEFAULT_VOTES_PER_REGEN_PERIOD"] = SMT_DEFAULT_VOTES_PER_REGEN_PERIOD;
   result["SMT_DEFAULT_PERCENT_CURATION_REWARDS"] = SMT_DEFAULT_PERCENT_CURATION_REWARDS;
#else
   result[ "DPN_ENABLE_SMT" ] = false;
#endif

   result["DBD_SYMBOL"] = DBD_SYMBOL;
   result["DPN_INITIAL_VOTE_POWER_RATE"] = DPN_INITIAL_VOTE_POWER_RATE;
   result["DPN_REDUCED_VOTE_POWER_RATE"] = DPN_REDUCED_VOTE_POWER_RATE;
   result["DPN_100_PERCENT"] = DPN_100_PERCENT;
   result["DPN_1_PERCENT"] = DPN_1_PERCENT;
   result["DPN_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = DPN_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["DPN_ACTIVE_CHALLENGE_COOLDOWN"] = DPN_ACTIVE_CHALLENGE_COOLDOWN;
   result["DPN_ACTIVE_CHALLENGE_FEE"] = DPN_ACTIVE_CHALLENGE_FEE;
   result["DPN_ADDRESS_PREFIX"] = DPN_ADDRESS_PREFIX;
   result["DPN_APR_PERCENT_MULTIPLY_PER_BLOCK"] = DPN_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["DPN_APR_PERCENT_MULTIPLY_PER_HOUR"] = DPN_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["DPN_APR_PERCENT_MULTIPLY_PER_ROUND"] = DPN_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["DPN_APR_PERCENT_SHIFT_PER_BLOCK"] = DPN_APR_PERCENT_SHIFT_PER_BLOCK;
   result["DPN_APR_PERCENT_SHIFT_PER_HOUR"] = DPN_APR_PERCENT_SHIFT_PER_HOUR;
   result["DPN_APR_PERCENT_SHIFT_PER_ROUND"] = DPN_APR_PERCENT_SHIFT_PER_ROUND;
   result["DPN_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = DPN_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["DPN_BANDWIDTH_PRECISION"] = DPN_BANDWIDTH_PRECISION;
   result["DPN_BENEFICIARY_LIMIT"] = DPN_BENEFICIARY_LIMIT;
   result["DPN_BLOCKCHAIN_PRECISION"] = DPN_BLOCKCHAIN_PRECISION;
   result["DPN_BLOCKCHAIN_PRECISION_DIGITS"] = DPN_BLOCKCHAIN_PRECISION_DIGITS;
   result["DPN_BLOCKCHAIN_HARDFORK_VERSION"] = DPN_BLOCKCHAIN_HARDFORK_VERSION;
   result["DPN_BLOCKCHAIN_VERSION"] = DPN_BLOCKCHAIN_VERSION;
   result["DPN_BLOCK_INTERVAL"] = DPN_BLOCK_INTERVAL;
   result["DPN_BLOCKS_PER_DAY"] = DPN_BLOCKS_PER_DAY;
   result["DPN_BLOCKS_PER_HOUR"] = DPN_BLOCKS_PER_HOUR;
   result["DPN_BLOCKS_PER_YEAR"] = DPN_BLOCKS_PER_YEAR;
   result["DPN_CASHOUT_WINDOW_SECONDS"] = DPN_CASHOUT_WINDOW_SECONDS;
   result["DPN_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = DPN_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["DPN_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = DPN_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["DPN_CHAIN_ID"] = DPN_CHAIN_ID;
   result["DPN_COMMENT_REWARD_FUND_NAME"] = DPN_COMMENT_REWARD_FUND_NAME;
   result["DPN_COMMENT_TITLE_LIMIT"] = DPN_COMMENT_TITLE_LIMIT;
   result["DPN_CONTENT_APR_PERCENT"] = DPN_CONTENT_APR_PERCENT;
   result["DPN_CONTENT_CONSTANT_HF0"] = DPN_CONTENT_CONSTANT_HF0;
   result["DPN_CONTENT_CONSTANT_HF21"] = DPN_CONTENT_CONSTANT_HF21;
   result["DPN_CONTENT_REWARD_PERCENT_HF16"] = DPN_CONTENT_REWARD_PERCENT_HF16;
   result["DPN_CONTENT_REWARD_PERCENT_HF21"] = DPN_CONTENT_REWARD_PERCENT_HF21;
   result["DPN_CONVERSION_DELAY"] = DPN_CONVERSION_DELAY;
   result["DPN_CONVERSION_DELAY_PRE_HF_16"] = DPN_CONVERSION_DELAY_PRE_HF_16;
   result["DPN_CREATE_ACCOUNT_DELEGATION_RATIO"] = DPN_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["DPN_CREATE_ACCOUNT_DELEGATION_TIME"] = DPN_CREATE_ACCOUNT_DELEGATION_TIME;
   result["DPN_CREATE_ACCOUNT_WITH_DPN_MODIFIER"] = DPN_CREATE_ACCOUNT_WITH_DPN_MODIFIER;
   result["DPN_CURATE_APR_PERCENT"] = DPN_CURATE_APR_PERCENT;
   result["DPN_CUSTOM_OP_DATA_MAX_LENGTH"] = DPN_CUSTOM_OP_DATA_MAX_LENGTH;
   result["DPN_CUSTOM_OP_ID_MAX_LENGTH"] = DPN_CUSTOM_OP_ID_MAX_LENGTH;
   result["DPN_DEFAULT_DBD_INTEREST_RATE"] = DPN_DEFAULT_DBD_INTEREST_RATE;
   result["DPN_DOWNVOTE_POOL_PERCENT_HF21"] = DPN_DOWNVOTE_POOL_PERCENT_HF21;
   result["DPN_EQUIHASH_K"] = DPN_EQUIHASH_K;
   result["DPN_EQUIHASH_N"] = DPN_EQUIHASH_N;
   result["DPN_FEED_HISTORY_WINDOW"] = DPN_FEED_HISTORY_WINDOW;
   result["DPN_FEED_HISTORY_WINDOW_PRE_HF_16"] = DPN_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["DPN_FEED_INTERVAL_BLOCKS"] = DPN_FEED_INTERVAL_BLOCKS;
   result["DPN_GENESIS_TIME"] = DPN_GENESIS_TIME;
   result["DPN_HARDFORK_REQUIRED_WITNESSES"] = DPN_HARDFORK_REQUIRED_WITNESSES;
   result["DPN_HF21_CONVERGENT_LINEAR_RECENT_CLAIMS"] = DPN_HF21_CONVERGENT_LINEAR_RECENT_CLAIMS;
   result["DPN_INFLATION_NARROWING_PERIOD"] = DPN_INFLATION_NARROWING_PERIOD;
   result["DPN_INFLATION_RATE_START_PERCENT"] = DPN_INFLATION_RATE_START_PERCENT;
   result["DPN_INFLATION_RATE_STOP_PERCENT"] = DPN_INFLATION_RATE_STOP_PERCENT;
   result["DPN_INIT_MINER_NAME"] = DPN_INIT_MINER_NAME;
   result["DPN_INIT_PUBLIC_KEY_STR"] = DPN_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["DPN_INIT_PRIVATE_KEY"] = DPN_INIT_PRIVATE_KEY;
#endif
   result["DPN_INIT_SUPPLY"] = DPN_INIT_SUPPLY;
   result["DPN_DBD_INIT_SUPPLY"] = DPN_DBD_INIT_SUPPLY;
   result["DPN_INIT_TIME"] = DPN_INIT_TIME;
   result["DPN_IRREVERSIBLE_THRESHOLD"] = DPN_IRREVERSIBLE_THRESHOLD;
   result["DPN_LIQUIDITY_APR_PERCENT"] = DPN_LIQUIDITY_APR_PERCENT;
   result["DPN_LIQUIDITY_REWARD_BLOCKS"] = DPN_LIQUIDITY_REWARD_BLOCKS;
   result["DPN_LIQUIDITY_REWARD_PERIOD_SEC"] = DPN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["DPN_LIQUIDITY_TIMEOUT_SEC"] = DPN_LIQUIDITY_TIMEOUT_SEC;
   result["DPN_MAX_ACCOUNT_CREATION_FEE"] = DPN_MAX_ACCOUNT_CREATION_FEE;
   result["DPN_MAX_ACCOUNT_NAME_LENGTH"] = DPN_MAX_ACCOUNT_NAME_LENGTH;
   result["DPN_MAX_ACCOUNT_WITNESS_VOTES"] = DPN_MAX_ACCOUNT_WITNESS_VOTES;
   result["DPN_MAX_ASSET_WHITELIST_AUTHORITIES"] = DPN_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["DPN_MAX_AUTHORITY_MEMBERSHIP"] = DPN_MAX_AUTHORITY_MEMBERSHIP;
   result["DPN_MAX_BLOCK_SIZE"] = DPN_MAX_BLOCK_SIZE;
   result["DPN_SOFT_MAX_BLOCK_SIZE"] = DPN_SOFT_MAX_BLOCK_SIZE;
   result["DPN_MAX_CASHOUT_WINDOW_SECONDS"] = DPN_MAX_CASHOUT_WINDOW_SECONDS;
   result["DPN_MAX_COMMENT_DEPTH"] = DPN_MAX_COMMENT_DEPTH;
   result["DPN_MAX_COMMENT_DEPTH_PRE_HF17"] = DPN_MAX_COMMENT_DEPTH_PRE_HF17;
   result["DPN_MAX_FEED_AGE_SECONDS"] = DPN_MAX_FEED_AGE_SECONDS;
   result["DPN_MAX_INSTANCE_ID"] = DPN_MAX_INSTANCE_ID;
   result["DPN_MAX_MEMO_SIZE"] = DPN_MAX_MEMO_SIZE;
   result["DPN_MAX_WITNESSES"] = DPN_MAX_WITNESSES;
   result["DPN_MAX_MINER_WITNESSES_HF0"] = DPN_MAX_MINER_WITNESSES_HF0;
   result["DPN_MAX_MINER_WITNESSES_HF17"] = DPN_MAX_MINER_WITNESSES_HF17;
   result["DPN_MAX_PERMLINK_LENGTH"] = DPN_MAX_PERMLINK_LENGTH;
   result["DPN_MAX_PROXY_RECURSION_DEPTH"] = DPN_MAX_PROXY_RECURSION_DEPTH;
   result["DPN_MAX_RATION_DECAY_RATE"] = DPN_MAX_RATION_DECAY_RATE;
   result["DPN_MAX_RESERVE_RATIO"] = DPN_MAX_RESERVE_RATIO;
   result["DPN_MAX_RUNNER_WITNESSES_HF0"] = DPN_MAX_RUNNER_WITNESSES_HF0;
   result["DPN_MAX_RUNNER_WITNESSES_HF17"] = DPN_MAX_RUNNER_WITNESSES_HF17;
   result["DPN_MAX_SATOSHIS"] = DPN_MAX_SATOSHIS;
   result["DPN_MAX_SHARE_SUPPLY"] = DPN_MAX_SHARE_SUPPLY;
   result["DPN_MAX_SIG_CHECK_DEPTH"] = DPN_MAX_SIG_CHECK_DEPTH;
   result["DPN_MAX_SIG_CHECK_ACCOUNTS"] = DPN_MAX_SIG_CHECK_ACCOUNTS;
   result["DPN_MAX_TIME_UNTIL_EXPIRATION"] = DPN_MAX_TIME_UNTIL_EXPIRATION;
   result["DPN_MAX_TRANSACTION_SIZE"] = DPN_MAX_TRANSACTION_SIZE;
   result["DPN_MAX_UNDO_HISTORY"] = DPN_MAX_UNDO_HISTORY;
   result["DPN_MAX_URL_LENGTH"] = DPN_MAX_URL_LENGTH;
   result["DPN_MAX_VOTE_CHANGES"] = DPN_MAX_VOTE_CHANGES;
   result["DPN_MAX_VOTED_WITNESSES_HF0"] = DPN_MAX_VOTED_WITNESSES_HF0;
   result["DPN_MAX_VOTED_WITNESSES_HF17"] = DPN_MAX_VOTED_WITNESSES_HF17;
   result["DPN_MAX_WITHDRAW_ROUTES"] = DPN_MAX_WITHDRAW_ROUTES;
   result["DPN_MAX_WITNESS_URL_LENGTH"] = DPN_MAX_WITNESS_URL_LENGTH;
   result["DPN_MIN_ACCOUNT_CREATION_FEE"] = DPN_MIN_ACCOUNT_CREATION_FEE;
   result["DPN_MIN_ACCOUNT_NAME_LENGTH"] = DPN_MIN_ACCOUNT_NAME_LENGTH;
   result["DPN_MIN_BLOCK_SIZE_LIMIT"] = DPN_MIN_BLOCK_SIZE_LIMIT;
   result["DPN_MIN_BLOCK_SIZE"] = DPN_MIN_BLOCK_SIZE;
   result["DPN_MIN_CONTENT_REWARD"] = DPN_MIN_CONTENT_REWARD;
   result["DPN_MIN_CURATE_REWARD"] = DPN_MIN_CURATE_REWARD;
   result["DPN_MIN_PERMLINK_LENGTH"] = DPN_MIN_PERMLINK_LENGTH;
   result["DPN_MIN_REPLY_INTERVAL"] = DPN_MIN_REPLY_INTERVAL;
   result["DPN_MIN_REPLY_INTERVAL_HF20"] = DPN_MIN_REPLY_INTERVAL_HF20;
   result["DPN_MIN_ROOT_COMMENT_INTERVAL"] = DPN_MIN_ROOT_COMMENT_INTERVAL;
   result["DPN_MIN_COMMENT_EDIT_INTERVAL"] = DPN_MIN_COMMENT_EDIT_INTERVAL;
   result["DPN_MIN_VOTE_INTERVAL_SEC"] = DPN_MIN_VOTE_INTERVAL_SEC;
   result["DPN_MINER_ACCOUNT"] = DPN_MINER_ACCOUNT;
   result["DPN_MINER_PAY_PERCENT"] = DPN_MINER_PAY_PERCENT;
   result["DPN_MIN_FEEDS"] = DPN_MIN_FEEDS;
   result["DPN_MINING_REWARD"] = DPN_MINING_REWARD;
   result["DPN_MINING_TIME"] = DPN_MINING_TIME;
   result["DPN_MIN_LIQUIDITY_REWARD"] = DPN_MIN_LIQUIDITY_REWARD;
   result["DPN_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = DPN_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["DPN_MIN_PAYOUT_DBD"] = DPN_MIN_PAYOUT_DBD;
   result["DPN_MIN_POW_REWARD"] = DPN_MIN_POW_REWARD;
   result["DPN_MIN_PRODUCER_REWARD"] = DPN_MIN_PRODUCER_REWARD;
   result["DPN_MIN_TRANSACTION_EXPIRATION_LIMIT"] = DPN_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["DPN_MIN_TRANSACTION_SIZE_LIMIT"] = DPN_MIN_TRANSACTION_SIZE_LIMIT;
   result["DPN_MIN_UNDO_HISTORY"] = DPN_MIN_UNDO_HISTORY;
   result["DPN_NULL_ACCOUNT"] = DPN_NULL_ACCOUNT;
   result["DPN_NUM_INIT_MINERS"] = DPN_NUM_INIT_MINERS;
   result["DPN_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = DPN_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["DPN_OWNER_AUTH_RECOVERY_PERIOD"] = DPN_OWNER_AUTH_RECOVERY_PERIOD;
   result["DPN_OWNER_CHALLENGE_COOLDOWN"] = DPN_OWNER_CHALLENGE_COOLDOWN;
   result["DPN_OWNER_CHALLENGE_FEE"] = DPN_OWNER_CHALLENGE_FEE;
   result["DPN_OWNER_UPDATE_LIMIT"] = DPN_OWNER_UPDATE_LIMIT;
   result["DPN_POST_AVERAGE_WINDOW"] = DPN_POST_AVERAGE_WINDOW;
   result["DPN_POST_REWARD_FUND_NAME"] = DPN_POST_REWARD_FUND_NAME;
   result["DPN_POST_WEIGHT_CONSTANT"] = DPN_POST_WEIGHT_CONSTANT;
   result["DPN_POW_APR_PERCENT"] = DPN_POW_APR_PERCENT;
   result["DPN_PRODUCER_APR_PERCENT"] = DPN_PRODUCER_APR_PERCENT;
   result["DPN_PROXY_TO_SELF_ACCOUNT"] = DPN_PROXY_TO_SELF_ACCOUNT;
   result["DPN_DBD_INTEREST_COMPOUND_INTERVAL_SEC"] = DPN_DBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["DPN_SECONDS_PER_YEAR"] = DPN_SECONDS_PER_YEAR;
   result["DPN_PROPOSAL_FUND_PERCENT_HF0"] = DPN_PROPOSAL_FUND_PERCENT_HF0;
   result["DPN_PROPOSAL_FUND_PERCENT_HF21"] = DPN_PROPOSAL_FUND_PERCENT_HF21;
   result["DPN_RECENT_RSHARES_DECAY_TIME_HF19"] = DPN_RECENT_RSHARES_DECAY_TIME_HF19;
   result["DPN_RECENT_RSHARES_DECAY_TIME_HF17"] = DPN_RECENT_RSHARES_DECAY_TIME_HF17;
   result["DPN_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = DPN_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["DPN_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = DPN_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["DPN_ROOT_POST_PARENT"] = DPN_ROOT_POST_PARENT;
   result["DPN_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = DPN_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["DPN_SAVINGS_WITHDRAW_TIME"] = DPN_SAVINGS_WITHDRAW_TIME;
   result["DPN_DBD_START_PERCENT_HF14"] = DPN_DBD_START_PERCENT_HF14;
   result["DPN_DBD_START_PERCENT_HF20"] = DPN_DBD_START_PERCENT_HF20;
   result["DPN_DBD_STOP_PERCENT_HF14"] = DPN_DBD_STOP_PERCENT_HF14;
   result["DPN_DBD_STOP_PERCENT_HF20"] = DPN_DBD_STOP_PERCENT_HF20;
   result["DPN_DBD_STOP_ADJUST"] = DPN_DBD_STOP_ADJUST;
   result["DPN_SECOND_CASHOUT_WINDOW"] = DPN_SECOND_CASHOUT_WINDOW;
   result["DPN_SOFT_MAX_COMMENT_DEPTH"] = DPN_SOFT_MAX_COMMENT_DEPTH;
   result["DPN_START_MINER_VOTING_BLOCK"] = DPN_START_MINER_VOTING_BLOCK;
   result["DPN_START_VESTING_BLOCK"] = DPN_START_VESTING_BLOCK;
   result["DPN_TEMP_ACCOUNT"] = DPN_TEMP_ACCOUNT;
   result["DPN_UPVOTE_LOCKOUT_HF7"] = DPN_UPVOTE_LOCKOUT_HF7;
   result["DPN_UPVOTE_LOCKOUT_HF17"] = DPN_UPVOTE_LOCKOUT_HF17;
   result["DPN_UPVOTE_LOCKOUT_SECONDS"] = DPN_UPVOTE_LOCKOUT_SECONDS;
   result["DPN_VESTING_FUND_PERCENT_HF16"] = DPN_VESTING_FUND_PERCENT_HF16;
   result["DPN_VESTING_WITHDRAW_INTERVALS"] = DPN_VESTING_WITHDRAW_INTERVALS;
   result["DPN_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = DPN_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["DPN_VESTING_WITHDRAW_INTERVAL_SECONDS"] = DPN_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["DPN_VOTE_DUST_THRESHOLD"] = DPN_VOTE_DUST_THRESHOLD;
   result["DPN_VOTING_MANA_REGENERATION_SECONDS"] = DPN_VOTING_MANA_REGENERATION_SECONDS;
   result["DPN_SYMBOL"] = DPN_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["DPN_VIRTUAL_SCHEDULE_LAP_LENGTH"] = DPN_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["DPN_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = DPN_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["DPN_MAX_LIMIT_ORDER_EXPIRATION"] = DPN_MAX_LIMIT_ORDER_EXPIRATION;
   result["DPN_DELEGATION_RETURN_PERIOD_HF0"] = DPN_DELEGATION_RETURN_PERIOD_HF0;
   result["DPN_DELEGATION_RETURN_PERIOD_HF20"] = DPN_DELEGATION_RETURN_PERIOD_HF20;
   result["DPN_RD_MIN_DECAY_BITS"] = DPN_RD_MIN_DECAY_BITS;
   result["DPN_RD_MAX_DECAY_BITS"] = DPN_RD_MAX_DECAY_BITS;
   result["DPN_RD_DECAY_DENOM_SHIFT"] = DPN_RD_DECAY_DENOM_SHIFT;
   result["DPN_RD_MAX_POOL_BITS"] = DPN_RD_MAX_POOL_BITS;
   result["DPN_RD_MAX_BUDGET_1"] = DPN_RD_MAX_BUDGET_1;
   result["DPN_RD_MAX_BUDGET_2"] = DPN_RD_MAX_BUDGET_2;
   result["DPN_RD_MAX_BUDGET_3"] = DPN_RD_MAX_BUDGET_3;
   result["DPN_RD_MAX_BUDGET"] = DPN_RD_MAX_BUDGET;
   result["DPN_RD_MIN_DECAY"] = DPN_RD_MIN_DECAY;
   result["DPN_RD_MIN_BUDGET"] = DPN_RD_MIN_BUDGET;
   result["DPN_RD_MAX_DECAY"] = DPN_RD_MAX_DECAY;
   result["DPN_ACCOUNT_SUBSIDY_PRECISION"] = DPN_ACCOUNT_SUBSIDY_PRECISION;
   result["DPN_WITNESS_SUBSIDY_BUDGET_PERCENT"] = DPN_WITNESS_SUBSIDY_BUDGET_PERCENT;
   result["DPN_WITNESS_SUBSIDY_DECAY_PERCENT"] = DPN_WITNESS_SUBSIDY_DECAY_PERCENT;
   result["DPN_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = DPN_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
   result["DPN_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = DPN_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
   result["DPN_DECAY_BACKSTOP_PERCENT"] = DPN_DECAY_BACKSTOP_PERCENT;
   result["DPN_BLOCK_GENERATION_POSTPONED_TX_LIMIT"] = DPN_BLOCK_GENERATION_POSTPONED_TX_LIMIT;
   result["DPN_PENDING_TRANSACTION_EXECUTION_LIMIT"] = DPN_PENDING_TRANSACTION_EXECUTION_LIMIT;
   result["DPN_TREASURY_ACCOUNT"] = DPN_TREASURY_ACCOUNT;
   result["DPN_TREASURY_FEE"] = DPN_TREASURY_FEE;
   result["DPN_PROPOSAL_MAINTENANCE_PERIOD"] = DPN_PROPOSAL_MAINTENANCE_PERIOD;
   result["DPN_PROPOSAL_MAINTENANCE_CLEANUP"] = DPN_PROPOSAL_MAINTENANCE_CLEANUP;
   result["DPN_PROPOSAL_SUBJECT_MAX_LENGTH"] = DPN_PROPOSAL_SUBJECT_MAX_LENGTH;
   result["DPN_PROPOSAL_MAX_IDS_NUMBER"] = DPN_PROPOSAL_MAX_IDS_NUMBER;

   return result;
}

} } // dpn::protocol
