#include <steemit/chain/get_config.hpp>
#include <steemit/chain/config.hpp>
#include <steemit/chain/protocol/types.hpp>

namespace steemit { namespace chain {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

   result[ "STEEMIT_SYMBOL" ] = STEEMIT_SYMBOL;
   result[ "STEEMIT_ADDRESS_PREFIX" ] = STEEMIT_ADDRESS_PREFIX;
   result[ "STEEMIT_MIN_ACCOUNT_NAME_LENGTH" ] = STEEMIT_MIN_ACCOUNT_NAME_LENGTH;
   result[ "STEEMIT_MAX_ACCOUNT_NAME_LENGTH" ] = STEEMIT_MAX_ACCOUNT_NAME_LENGTH;
   result[ "STEEMIT_MAX_SHARE_SUPPLY" ] = STEEMIT_MAX_SHARE_SUPPLY;
   result[ "STEEMIT_MAX_SIG_CHECK_DEPTH" ] = STEEMIT_MAX_SIG_CHECK_DEPTH;
   result[ "STEEMIT_MIN_TRANSACTION_SIZE_LIMIT" ] = STEEMIT_MIN_TRANSACTION_SIZE_LIMIT;
   result[ "STEEMIT_BLOCK_INTERVAL" ] = STEEMIT_BLOCK_INTERVAL;
   result[ "STEEMIT_MAX_TRANSACTION_SIZE" ] = STEEMIT_MAX_TRANSACTION_SIZE;
   result[ "STEEMIT_MAX_BLOCK_SIZE" ] = STEEMIT_MAX_BLOCK_SIZE;
   result[ "STEEMIT_MAX_TIME_UNTIL_EXPIRATION" ] = STEEMIT_MAX_TIME_UNTIL_EXPIRATION;
   result[ "STEEMIT_MIN_UNDO_HISTORY" ] = STEEMIT_MIN_UNDO_HISTORY;
   result[ "STEEMIT_MAX_UNDO_HISTORY" ] = STEEMIT_MAX_UNDO_HISTORY;
   result[ "STEEMIT_MIN_BLOCK_SIZE_LIMIT" ] = STEEMIT_MIN_BLOCK_SIZE_LIMIT;
   result[ "STEEMIT_MIN_TRANSACTION_EXPIRATION_LIMIT" ] = STEEMIT_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result[ "STEEMIT_MAX_INSTANCE_ID" ] = STEEMIT_MAX_INSTANCE_ID;
   result[ "STEEMIT_100_PERCENT" ] = STEEMIT_100_PERCENT;
   result[ "STEEMIT_1_PERCENT" ] = STEEMIT_1_PERCENT;
   result[ "STEEMIT_MAX_AUTHORITY_MEMBERSHIP" ] = STEEMIT_MAX_AUTHORITY_MEMBERSHIP;
   result[ "STEEMIT_MAX_MINERS" ] = STEEMIT_MAX_MINERS;
   result[ "STEEMIT_MAX_URL_LENGTH" ] = STEEMIT_MAX_URL_LENGTH;
   result[ "STEEMIT_MINER_ACCOUNT" ] = STEEMIT_MINER_ACCOUNT;
   result[ "STEEMIT_NULL_ACCOUNT" ] = STEEMIT_NULL_ACCOUNT;
   result[ "STEEMIT_TEMP_ACCOUNT" ] = STEEMIT_TEMP_ACCOUNT;

   return result;
}

} } // steemit::chain
